# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDU4ZTE0NmM0Y2EyODdhZjg3MmQxNmRkY2FmYWJmZDk2OGE2ZDE2YzVjYjE0NThhMzcwYTk4YjMxNThlNmIyYjAxYTgzZjc2OThmM2JmZDhhYTI2NTRkODc4YTZjOWQxZjFhYTliYzljOTRmMTRiNGFkZDJmM2U5OThjYzJkNTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
